# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget wx::wxregex wx::wxzlib wx::wxexpat wx::wxjpeg wx::wxpng wx::wxtiff wx::wxmono)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target wx::wxregex
add_library(wx::wxregex STATIC IMPORTED)

set_target_properties(wx::wxregex PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE"
)

# Create imported target wx::wxzlib
add_library(wx::wxzlib STATIC IMPORTED)

set_target_properties(wx::wxzlib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE"
)

# Create imported target wx::wxexpat
add_library(wx::wxexpat STATIC IMPORTED)

set_target_properties(wx::wxexpat PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE"
)

# Create imported target wx::wxjpeg
add_library(wx::wxjpeg STATIC IMPORTED)

set_target_properties(wx::wxjpeg PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE"
)

# Create imported target wx::wxpng
add_library(wx::wxpng STATIC IMPORTED)

set_target_properties(wx::wxpng PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:wx::wxzlib>"
)

# Create imported target wx::wxtiff
add_library(wx::wxtiff STATIC IMPORTED)

set_target_properties(wx::wxtiff PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:wx::wxzlib>;\$<LINK_ONLY:wx::wxjpeg>"
)

# Create imported target wx::wxmono
add_library(wx::wxmono STATIC IMPORTED)

set_target_properties(wx::wxmono PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE;__WXMSW__"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/vc_x64_lib/mswu\$<\$<CONFIG:Debug>:d>;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "kernel32;user32;gdi32;comdlg32;winspool;winmm;shell32;shlwapi;comctl32;ole32;oleaut32;uuid;rpcrt4;advapi32;version;ws2_32;wininet;oleacc;uxtheme;\$<LINK_ONLY:wx::wxzlib>;\$<LINK_ONLY:wx::wxregex>;\$<LINK_ONLY:ws2_32>;\$<LINK_ONLY:winhttp>;\$<LINK_ONLY:wx::wxjpeg>;\$<LINK_ONLY:wx::wxpng>;\$<LINK_ONLY:wx::wxtiff>;\$<LINK_ONLY:winmm>;\$<LINK_ONLY:wx::wxexpat>;opengl32;glu32"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/wxWidgetsTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
